export { default as Intro } from './intro/Intro.jsx';
export { default as Synq } from './synq/Synq.jsx';
export { default as Liv } from './liv/Liv.jsx';
export { default as Tv } from './tv/Tv.jsx';
export { default as Fankens } from './fankens/Fankens.jsx';
export { default as Dl } from './dl/Dl.jsx';
export { default as Piedras } from './piedras/Piedras.jsx';
export { default as Tt } from './tt/Tt.jsx';
export { default as Personal } from './work_play/Personal.jsx';